export const projects = [
	{
		slug: 'mintube',
		imageCount: 4,
		title: 'MinTube',
		subtitle: 'Fullstack Lightweight Media Player',
		description: 'Node.js-based streaming service with a caching layer to support low-bandwidth playback and accessibility.',
		image: './src/assets/projects/mintube/thumb.png',
		tags: ['JavaScript', 'React', 'Node.js', 'Electron'],
		githubUrl: `https://github.com/GrayMiracle/MinTube`,
	},
	{
		slug: 'simengine',
		imageCount: 5,
		title: 'Cloud-Based Simulation Engine',
		subtitle: 'Backend Simulation Engine',
		description: 'A modular backend simulation engine supporting 30+ unit configurations with dynamic trait resolution and various interaction logic.',
		image: './src/assets/projects/simengine/thumb.png',
		tags: ['JavaScript', 'React', 'Firestore', 'Vercel'],
		githubUrl: `https://github.com/GrayMiracle/MyGachaIsBlue`,
		liveUrl: `https://mygachaisblue.vercel.app/`
	},
	{
		slug: 'portableai',
		imageCount: 4,
		title: 'PortableAI',
		subtitle: 'Local AI Inference Service',
		description: 'A Flask backend service for local AI inference, handling request routing, state management, and voice pipelines.',
		image: './src/assets/projects/portableai/thumb.png',
		tags: ['Python', 'TypeScript', 'React', 'MySQL', 'Flask'],
		githubUrl: `https://github.com/GrayMiracle/SovitsCLI`,
	},
	{
		slug: 'dokkandata',
		imageCount: 4,
		title: 'Dokkan Data',
		subtitle: 'Convenient Database Collection Tool',
		description: 'A one click data export tool that gather data for every Dokkan character, allowing users to download up-to-date CSV files with one click without datamining or manually searching character pages.',
		image: './src/assets/projects/dokkandata/thumb.png',
		tags: ['Python', 'Selenium', 'TypeScript', 'React', 'CSV'],
		githubUrl: `https://github.com/GrayMiracle/DokkanData`,
	},
	{
		slug: 'dokkanguessr',
		imageCount: 4,
		title: 'Dokkan Guessr',
		subtitle: 'Dokkan OST Guessing Discord Bot',
		description: 'A Discord bot that turns Dokkan Battle OSTs into an interactive guessing game, using audio playback, answer validation, and score tracking for multiplayer challenges across different servers.',
		image: './src/assets/projects/dokkanguessr/thumb.png',
		tags: ['Python', 'Discord', 'FFMPpeg'],
		githubUrl: `https://github.com/GrayMiracle/GuessDokkanOst`,
	},
	{
		slug: 'mlpassivepredictor',
		imageCount: 4,
		title: 'ML Passive Predictor',
		subtitle: 'Machine Learning Passive Income Predictor',
		description: 'A machine learning tool that analyzes historical passive values from datasets to train GPT-2 to generate year-accurate passive predictions and visualize trends over time.',
		image: './src/assets/projects/mlpassivepredictor/thumb.png',
		tags: ['Python', 'Transformers', 'Pandas', 'NumPy'],
		githubUrl: `https://github.com/GrayMiracle/DokkanML`,
	},
	{
		slug: 'discaitts',
		imageCount: 4,
		title: 'Discord AI TTS Bot',
		subtitle: 'AI Bot with Text-to-Speech as a discord bot',
		description: 'An LLM integrated with a discord bot with customizable GPT-SoVITS TTS pipelines, reading messages from given channels and playing responses in voice chat.',
		image: './src/assets/projects/discaitts/thumb.png',
		tags: ['Python', 'Discord', 'GPT_SoVITS'],
		githubUrl: `https://github.com/GrayMiracle/RemGPT`,
	},
	{
		slug: 'santaobby',
		imageCount: 4,
		title: 'Santa Obby',
		subtitle: 'Unique Obstacle Course Creation Challenge',
		description: 'A Roblox obstacle course designed as a part of a game creation challenge for Winter with a unique twist for each stage, utilizing unique gameplay mechanics to provide a fresh and engaging experience.',
		image: './src/assets/projects/santaobby/Thumb.png',
		tags: ['Lua', 'Roblox Studio'],
		liveUrl: `https://www.roblox.com/games/70595312283781/Obby-Into-Santa`
	},
]